version: '3.9'

networks:
  food-delivery-api-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fooddeliveryapi
    ports:
      - 3306:3306
    networks:
      - food-delivery-api-network
    volumes:
      - ./db_data:/var/lib/mysql
  food-delivery-api:
    command: ["/wait-for-it.sh", "mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    image: food-delivery-api:${API_VERSION}
    environment: 
      DB_HOST: mysql
      SPRING_PROFILES_ACTIVE: development
    networks:
      - food-delivery-api-network
    depends_on:
      - mysql
    deploy:
      replicas: 2
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - 80:80
    networks:
      - food-delivery-api-network
    depends_on:
      - food-delivery-api